export const content = {
    common: {
        appName: "Acutia Lens",
        loading: "Carregando...",
        error: "Ocorreu um erro",
        retry: "Tentar novamente",
        save: "Salvar",
        cancel: "Cancelar",
        back: "Voltar",
        next: "Próximo",
        finish: "Finalizar",
        close: "Fechar",
        search: "Buscar",
        filter: "Filtrar",
        clearFilters: "Limpar filtros",
        empty: "Nada encontrado",
    },
    nav: {
        home: "Início",
        events: "Eventos",
        find: "Encontrar",
        gallery: "Galeria",
        cart: "Carrinho",
        admin: "Admin",
        docs: "Docs",
    },
    home: {
        hero: {
            title: "Encontre suas fotos",
            highlight: "em segundos",
            subtitle: "A Acutia Lens reúne as fotos profissionais do seu evento em um só lugar. Envie uma selfie para encontrar as imagens em que você aparece, escolha as favoritas e baixe em alta qualidade com segurança <strong class='text-foreground'>— com gestão prática para organizadores e fotógrafos.</strong>",
            ctaFind: "Encontrar minhas fotos",
            ctaEvents: "Ver eventos disponíveis",
        },
        features: {
            title: "Como funciona",
            search: {
                title: "Busca Facial",
                description: "Envie uma selfie e nossa IA encontra você em milhares de fotos em segundos.",
            },
            quality: {
                title: "Alta Qualidade",
                description: "Fotos profissionais em alta resolução, prontas para postar ou imprimir.",
            },
            instant: {
                title: "Entrega Imediata",
                description: "Comprou, baixou. Sem espera, direto no seu dispositivo.",
            },
        },
    },
    events: {
        title: "Eventos Recentes",
        subtitle: "Cobertura fotográfica completa dos últimos jogos e eventos.",
        status: {
            active: "Disponível",
            ended: "Encerrado",
        },
        filterByStatus: "Filtrar por status",
        all: "Todos",
    },
    eventDetail: {
        backToEvents: "Voltar para eventos",
        photographer: "Fotógrafo(a)",
        photosAvailable: "fotos disponíveis",
        addToCart: "Adicionar ao carrinho",
        inCart: "No carrinho",
        removeFromCart: "Remover",
    },
    find: {
        title: "Encontrar minhas fotos",
        subtitle: "Envie uma selfie nítida para que nossa IA possa encontrar você nos eventos recentes.",
        uploadLabel: "Clique para enviar sua selfie",
        uploadHelp: "Formatos: JPG ou PNG. Máx 5MB.",
        analyzing: "Analisando fotos...",
        resultsTitle: "Encontramos você!",
        noResults: "Nenhuma foto encontrada. Tente outra selfie ou procure manualmente nos eventos.",
        lgpd: {
            title: "Consentimento de Uso",
            text: "Ao enviar sua foto, você concorda que ela será usada apenas momentaneamente para buscar correspondências em nosso banco de imagens. A foto de busca não é armazenada.",
            accept: "Li e concordo com os termos",
        },
    },
    cart: {
        title: "Seu Carrinho",
        empty: "Seu carrinho está vazio.",
        emptyCta: "Ver eventos",
        total: "Total",
        checkout: "Finalizar Compra",
        summary: "Resumo do Pedido",
        item: "item",
        items: "itens",
    },
    checkout: {
        title: "Finalizar Compra",
        personalData: "Dados Pessoais",
        payment: "Pagamento",
        nameLabel: "Nome completo",
        emailLabel: "E-mail",
        paymentMethod: "Forma de Pagamento",
        details: "Detalhes do Pagamento",
        payWithPix: "Pagar com PIX",
        payWithCard: "Cartão de Crédito",
        processing: "Processando...",
        success: "Compra realizada com sucesso!",
    },
    order: {
        title: "Pedido Confirmado!",
        subtitle: "Obrigado por sua compra. Suas fotos já estão liberadas para download.",
        download: "Baixar foto em alta resolução",
        orderId: "Pedido #",
        date: "Data",
        total: "Total pago",
    },
    admin: {
        dashboard: "Painel Administrativo",
        stats: "Estatísticas Gerais",
    },
};
